[program:comfyui-worker-server]
directory=@APP_DIR@
command=/usr/bin/node @APP_DIR@/dist/index.js
autostart=true
autorestart=true
startsecs=1
startretries=999
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/pai/comfyui-worker-server.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile=/var/log/pai/comfyui-worker-server.err.log
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=5

[program:comfyui-worker-consumer]
directory=@APP_DIR@
command=/usr/bin/node @APP_DIR@/dist/queue/worker-cli.js
environment=COMFYUI_WORKER_DATABASE_SYNC="false"
autostart=true
autorestart=true
startsecs=1
startretries=999
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/pai/comfyui-worker-consumer.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile=/var/log/pai/comfyui-worker-consumer.err.log
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=5
