/**
 * GraphQL operation generator — `npm run graphql:operations`.
 *
 * Derives one operation document per root field (every Query, Mutation and
 * Subscription field) from the locally-downloaded SDL, so the codegen SDK ends
 * up with a typed request method for *all* of the schema's operations without
 * anyone hand-writing 24 `.graphql` files.
 *
 * Output goes to operations/generated/ (wiped and rebuilt each run, so a field
 * removed from the schema disappears from the SDK too). Hand-written documents
 * — bespoke selection sets, multi-field queries — live in operations/custom/
 * and are never touched here; codegen globs both folders.
 *
 * Offline by design: reads the committed SDL, not the network. Run
 * `npm run graphql:schema` first if the SDL is stale.
 *
 * Per-source naming (paiPlatform*) keeps a second GraphQL endpoint addable
 * side-by-side. See docs/graphql-sdk.md.
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSchema, Kind, OperationTypeNode, print, validate } from 'graphql';
import { buildOperationNodeForField } from '@graphql-tools/utils';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SCHEMA_PATH = resolve(ROOT, 'src/platform/graphql/schema/paiPlatform.graphql');
const OUTPUT_DIR = resolve(ROOT, 'src/platform/graphql/operations/generated');

// Selection depth for nested object fields. Deep enough to be useful, shallow
// enough to keep documents readable and avoid traversing large graphs.
const DEPTH_LIMIT = 3;
const CIRCULAR_REFERENCE_DEPTH = 1;

function loadSchema() {
  let sdl;
  try {
    sdl = readFileSync(SCHEMA_PATH, 'utf-8');
  } catch {
    throw new Error(`Schema SDL not found at ${SCHEMA_PATH}. Run "npm run graphql:schema" first.`);
  }
  return buildSchema(sdl);
}

/**
 * Build a valid operation document for a single root field.
 *
 * buildOperationNodeForField can emit colliding variable names when deeply
 * nested fields share an argument name (a known limitation). We validate the
 * result against the schema and progressively shrink the selection depth until
 * the document is valid, so the generator self-heals as the schema evolves
 * instead of emitting documents codegen will later reject.
 */
function buildValidOperation(schema, kind, field) {
  for (let depth = DEPTH_LIMIT; depth >= 1; depth -= 1) {
    const operationNode = buildOperationNodeForField({
      schema,
      kind,
      field,
      depthLimit: depth,
      circularReferenceDepth: CIRCULAR_REFERENCE_DEPTH,
    });
    const document = { kind: Kind.DOCUMENT, definitions: [operationNode] };
    const errors = validate(schema, document);
    if (errors.length === 0) {
      return { operationNode, depth };
    }
  }
  return null;
}

const KINDS = [
  { kind: OperationTypeNode.QUERY, rootName: 'getQueryType' },
  { kind: OperationTypeNode.MUTATION, rootName: 'getMutationType' },
  { kind: OperationTypeNode.SUBSCRIPTION, rootName: 'getSubscriptionType' },
];

function main() {
  const schema = loadSchema();

  // Rebuild from scratch so deleted schema fields don't leave stale documents.
  rmSync(OUTPUT_DIR, { recursive: true, force: true });

  let written = 0;
  const skipped = [];

  for (const { kind, rootName } of KINDS) {
    const rootType = schema[rootName]();
    if (!rootType) continue;

    const fields = Object.keys(rootType.getFields()).sort();
    if (fields.length === 0) continue;

    const dir = resolve(OUTPUT_DIR, kind);
    mkdirSync(dir, { recursive: true });

    for (const field of fields) {
      try {
        const built = buildValidOperation(schema, kind, field);
        if (!built) {
          skipped.push({ field: `${kind}.${field}`, reason: 'no valid document even at depth 1' });
          continue;
        }
        const depthNote = built.depth < DEPTH_LIMIT ? ` (depth reduced to ${built.depth})` : '';
        const document = `# AUTO-GENERATED by scripts/generateGraphqlOperations.mjs — do not edit.\n# Source field: ${kind}.${field}${depthNote}\n${print(built.operationNode)}\n`;
        writeFileSync(resolve(dir, `${field}.graphql`), document, 'utf-8');
        written += 1;
      } catch (error) {
        skipped.push({ field: `${kind}.${field}`, reason: error?.message || String(error) });
      }
    }
  }

  console.log(`[graphql:operations] wrote ${written} operation document(s) to ${OUTPUT_DIR}`);
  if (skipped.length > 0) {
    console.warn(`[graphql:operations] skipped ${skipped.length} field(s):`);
    for (const item of skipped) {
      console.warn(`  - ${item.field}: ${item.reason}`);
    }
  }
}

main();
